In [9]:
import pandas as pd
import re

In [2]:
df = pd.read_excel('./eurobarometer_data/eb_105.xlsx', sheet_name='QB7a', header=8)

In [4]:
df

,<<Back to content,Unnamed: 1,UE27\nEU27,BE,BG,CZ,DK,DEW,DE,DEE,...,MT,NL,AT,PL,PT,RO,SI,SK,FI,SE
0,NaN,Total,26415,1014,1015,1036,1001,1220,1515,295,...,502,1012,1004,1025,1052,1054,1009,1003,1009,1026
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"L’économie (par exemple, la compétitivité)",3205,110,182,127,58,163,215,52,...,55,46,146,89,77,114,169,141,143,88
3,NaN,"Economy (e.g., competitiveness)",0.12,0.11,0.18,0.12,0.06,0.13,0.14,0.18,...,0.11,0.05,0.15,0.09,0.07,0.11,0.17,0.14,0.14,0.09
4,NaN,L'emploi,1999,89,70,44,13,20,24,5,...,37,12,60,55,211,110,19,63,97,23
5,NaN,Employment,0.08,0.09,0.07,0.04,0.01,0.02,0.02,0.02,...,0.07,0.01,0.06,0.05,0.2,0.1,0.02,0.06,0.1,0.02
6,NaN,L'égalité sociale,1401,55,135,60,48,71,92,21,...,27,45,80,54,110,52,67,64,44,40
7,NaN,Social equality,0.05,0.05,0.13,0.06,0.05,0.06,0.06,0.07,...,0.05,0.04,0.08,0.05,0.11,0.05,0.07,0.06,0.04,0.04
8,NaN,L'éducation et la formation,1038,29,18,29,10,42,52,10,...,32,25,39,27,37,70,37,38,29,20
9,NaN,Education and training,0.04,0.03,0.02,0.03,0.01,0.04,0.03,0.03,...,0.06,0.03,0.04,0.03,0.04,0.07,0.04,0.04,0.03,0.02
10,NaN,La recherche et l'innovation,915,26,25,36,19,40,49,10,...,20,20,47,33,22,42,15,22,50,45
11,NaN,Research and innovation,0.04,0.03,0.02,0.04,0.02,0.03,0.03,0.03,...,0.04,0.02,0.05,0.03,0.02,0.04,0.01,0.02,0.05,0.04
12,NaN,Le climat et l'environnement,2245,108,26,34,254,115,145,31,...,44,150,88,40,29,29,48,30,92,279
13,NaN,Climate and the environment,0.09,0.11,0.03,0.03,0.25,0.09,0.1,0.1,...,0.09,0.15,0.09,0.04,0.03,0.03,0.05,0.03,0.09,0.27
14,NaN,La migration,2385,154,47,128,69,127,165,38,...,88,171,97,57,53,49,122,61,34,58
15,NaN,Migration,0.09,0.15,0.05,0.13,0.07,0.1,0.11,0.13,...,0.18,0.17,0.1,0.05,0.05,0.05,0.12,0.06,0.03,0.06
16,NaN,La sécurité et la défense,4740,164,182,252,300,257,305,47,...,69,273,142,297,120,176,99,167,278,183
17,NaN,Security and defence,0.18,0.16,0.18,0.24,0.3,0.21,0.2,0.16,...,0.14,0.27,0.14,0.29,0.11,0.17,0.1,0.17,0.28,0.18
18,NaN,L'agriculture,1178,52,65,31,35,30,35,5,...,13,21,42,42,45,76,117,73,45,33
19,NaN,Agriculture,0.04,0.05,0.06,0.03,0.04,0.02,0.02,0.01,...,0.03,0.02,0.04,0.04,0.04,0.07,0.11,0.07,0.04,0.03
20,NaN,"L’industrie (par exemple, la réduction de la c...",1022,36,43,52,16,71,88,17,...,9,19,32,72,24,63,46,62,16,17
21,NaN,"Industry (e.g., reduction of the administrativ...",0.04,0.04,0.04,0.05,0.02,0.06,0.06,0.06,...,0.02,0.02,0.03,0.07,0.02,0.06,0.04,0.06,0.02,0.02
22,NaN,Le commerce avec des pays hors de l'UE,532,23,22,34,24,19,24,5,...,6,25,27,28,12,39,27,20,28,23
23,NaN,Trade with countries outside the EU,0.02,0.02,0.02,0.04,0.02,0.02,0.02,0.02,...,0.01,0.02,0.03,0.03,0.01,0.04,0.03,0.02,0.03,0.02
24,NaN,La santé,2067,57,63,65,38,32,46,14,...,48,36,50,84,246,75,123,109,25,9
25,NaN,Health,0.08,0.06,0.06,0.06,0.04,0.03,0.03,0.05,...,0.1,0.04,0.05,0.08,0.24,0.07,0.12,0.11,0.02,0.01
26,NaN,La démocratie,1227,41,21,23,32,91,108,18,...,21,47,55,53,17,41,18,37,46,109
27,NaN,Democracy,0.05,0.04,0.02,0.02,0.03,0.07,0.07,0.06,...,0.04,0.05,0.05,0.05,0.02,0.04,0.02,0.04,0.05,0.11
28,NaN,Les technologies numériques (y compris les pla...,876,25,50,29,37,45,56,11,...,21,51,43,37,21,45,31,49,28,24
29,NaN,Digital technologies (including social media p...,0.03,0.02,0.05,0.03,0.04,0.04,0.04,0.04,...,0.04,0.05,0.04,0.04,0.02,0.04,0.03,0.05,0.03,0.02
30,NaN,La lutte contre la manipulation de l'information,1125,41,28,34,31,73,84,11,...,10,53,41,47,13,44,68,65,39,68
31,NaN,Countering information manipulation,0.04,0.04,0.03,0.03,0.03,0.06,0.06,0.04,...,0.02,0.05,0.04,0.05,0.01,0.04,0.07,0.07,0.04,0.07
32,NaN,Autre (SPONTANÉ),61,3,7,0,1,3,3,1,...,0,0,8,2,0,3,0,2,1,0
33,NaN,Other (SPONTANEOUS),-,-,0.01,-,-,-,-,-,...,-,-,0.01,-,-,-,-,-,-,-
34,NaN,Aucun (SPONTANÉ),92,1,4,13,0,6,7,1,...,0,14,5,0,1,2,2,0,0,4
35,NaN,None (SPONTANEOUS),-,-,-,0.01,-,0.01,-,-,...,-,0.01,-,-,-,-,-,-,-,-
36,NaN,Ne sait pas,306,0,27,44,14,17,17,0,...,2,2,2,10,14,24,2,2,14,1
37,NaN,Don't know,0.01,-,0.03,0.04,0.01,0.01,0.01,-,...,-,-,-,0.01,0.01,0.02,-,-,0.01,-

## VERY IMPORTANT!
Double-check all the french columns. Their presence means that it was not a correct column copied!!!
The condition about BE < 1 fails in come cases, like below:

In [20]:
df = pd.read_excel('./eurobarometer_data/eb_105.xlsx', sheet_name='QB7a', header=8)
df = df.drop(columns={'<<Back to content','UE27\nEU27', 'UE27\\nEU27'},errors='ignore')
num_cols = df.columns.drop('Unnamed: 1')
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')
df = df[df['BE'] < 1]
df.set_index('Unnamed: 1',inplace=True)
df = df.T
df.index.name = 'country'
df.reset_index(inplace=True)
df.columns.name = None

cleaned_cols = []
for col in df.columns:
    if col == 'country':
        cleaned_cols.append(col)
    else:
        col_str = str(col).lower().strip()
        col_str = col_str.replace("'", "").replace(",", "")
        col_str = col_str.replace(":", "_").replace(" ", "_")
        col_str = re.sub(r'_+', '_', col_str)  # collapses ___ down to _
        cleaned_cols.append(col_str)
df.columns = cleaned_cols

mapping_df = pd.read_csv('mapping_columns.csv')
mapping_df['raw_phrase'] = mapping_df['raw_phrase'].astype(str).str.lower().str.strip()
mapping_df['clean_phrase'] = mapping_df['clean_phrase'].astype(str).str.lower().str.strip()
        
mapping_df['phrase_len'] = mapping_df['raw_phrase'].str.len()
mapping_df = mapping_df.sort_values(by='phrase_len', ascending=False)
column_replacements = dict(zip(mapping_df['raw_phrase'], mapping_df['clean_phrase']))
mapping_df.to_csv('mapping_columns.csv', index=False)

for long_phrase, short_phrase in column_replacements.items():
    df.columns = df.columns.str.replace(long_phrase, short_phrase, regex=False)

df

,country,econmy_(e.g._competitiveness),employment,social_equality,education_and_training,research_and_innvation,climate_and_the_environment,migration,security_and_defence,agriculture,industry_admin_burden,trade_with_countries_outside_the_eu,health,democracy,digital_technlogies_(including_social_media_platforms)_and_digital_transformation,countering_information_manipulation,ne_sait_pas
0,BE,0.11,0.09,0.05,0.03,0.03,0.11,0.15,0.16,0.05,0.04,0.02,0.06,0.04,0.02,0.04,0.0
1,BG,0.18,0.07,0.13,0.02,0.02,0.03,0.05,0.18,0.06,0.04,0.02,0.06,0.02,0.05,0.03,27.0
2,CZ,0.12,0.04,0.06,0.03,0.04,0.03,0.13,0.24,0.03,0.05,0.04,0.06,0.02,0.03,0.03,44.0
3,DK,0.06,0.01,0.05,0.01,0.02,0.25,0.07,0.30,0.04,0.02,0.02,0.04,0.03,0.04,0.03,14.0
4,DEW,0.13,0.02,0.06,0.04,0.03,0.09,0.10,0.21,0.02,0.06,0.02,0.03,0.07,0.04,0.06,17.0
5,DE,0.14,0.02,0.06,0.03,0.03,0.10,0.11,0.20,0.02,0.06,0.02,0.03,0.07,0.04,0.06,17.0
6,DEE,0.18,0.02,0.07,0.03,0.03,0.10,0.13,0.16,0.01,0.06,0.02,0.05,0.06,0.04,0.04,0.0
7,EE,0.20,0.05,0.04,0.07,0.05,0.03,0.04,0.20,0.06,0.05,0.02,0.05,0.02,0.05,0.04,20.0
8,IE,0.09,0.06,0.04,0.05,0.02,0.10,0.13,0.15,0.04,0.02,0.03,0.17,0.03,0.03,0.03,7.0
9,EL,0.27,0.12,0.06,0.05,0.02,0.04,0.07,0.13,0.05,0.01,0.01,0.09,0.05,0.02,0.01,2.0
10,ES,0.13,0.15,0.04,0.05,0.03,0.04,0.11,0.08,0.06,0.03,0.02,0.13,0.04,0.02,0.04,18.0
11,FR,0.09,0.09,0.05,0.06,0.03,0.12,0.08,0.16,0.08,0.02,0.01,0.10,0.02,0.02,0.04,16.0
12,HR,0.17,0.08,0.04,0.05,0.02,0.06,0.06,0.16,0.07,0.06,0.02,0.07,0.02,0.04,0.05,12.0
13,IT,0.15,0.11,0.03,0.03,0.06,0.09,0.07,0.16,0.02,0.03,0.03,0.07,0.05,0.05,0.04,6.0
14,CY,0.17,0.06,0.03,0.07,0.02,0.03,0.18,0.17,0.04,0.01,NaN,0.12,0.06,0.01,0.02,3.0
15,LV,0.14,0.05,0.06,0.06,0.02,0.01,0.07,0.23,0.06,0.03,0.03,0.15,0.03,0.01,0.02,28.0
16,LT,0.13,0.06,0.08,0.05,0.02,0.02,0.06,0.33,0.03,0.02,0.03,0.09,0.01,0.03,0.03,7.0
17,LU,0.06,0.06,0.07,0.07,0.04,0.10,0.09,0.21,0.03,0.03,0.01,0.05,0.07,0.05,0.05,3.0
18,HU,0.14,0.04,0.07,0.04,0.03,0.08,0.10,0.15,0.05,0.04,0.03,0.11,0.06,0.02,0.03,5.0
19,MT,0.11,0.07,0.05,0.06,0.04,0.09,0.18,0.14,0.03,0.02,0.01,0.10,0.04,0.04,0.02,2.0
20,NL,0.05,0.01,0.04,0.03,0.02,0.15,0.17,0.27,0.02,0.02,0.02,0.04,0.05,0.05,0.05,2.0
21,AT,0.15,0.06,0.08,0.04,0.05,0.09,0.10,0.14,0.04,0.03,0.03,0.05,0.05,0.04,0.04,2.0
22,PL,0.09,0.05,0.05,0.03,0.03,0.04,0.05,0.29,0.04,0.07,0.03,0.08,0.05,0.04,0.05,10.0
23,PT,0.07,0.20,0.11,0.04,0.02,0.03,0.05,0.11,0.04,0.02,0.01,0.24,0.02,0.02,0.01,14.0
24,RO,0.11,0.10,0.05,0.07,0.04,0.03,0.05,0.17,0.07,0.06,0.04,0.07,0.04,0.04,0.04,24.0
25,SI,0.17,0.02,0.07,0.04,0.01,0.05,0.12,0.10,0.11,0.04,0.03,0.12,0.02,0.03,0.07,2.0
26,SK,0.14,0.06,0.06,0.04,0.02,0.03,0.06,0.17,0.07,0.06,0.02,0.11,0.04,0.05,0.07,2.0
27,FI,0.14,0.10,0.04,0.03,0.05,0.09,0.03,0.28,0.04,0.02,0.03,0.02,0.05,0.03,0.04,14.0
28,SE,0.09,0.02,0.04,0.02,0.04,0.27,0.06,0.18,0.03,0.02,0.02,0.01,0.11,0.02,0.07,1.0

In [18]:
df

,country,econmy_(e.g._competitiveness),employment,social_equality,education_and_training,research_and_innvation,climate_and_the_environment,migration,security_and_defence,agriculture,industry_admin_burden,trade_with_countries_outside_the_eu,health,democracy,dig_tech_dig_transf,countering_information_manipulation,ne_sait_pas
0,BE,0.11,0.09,0.05,0.03,0.03,0.11,0.15,0.16,0.05,0.04,0.02,0.06,0.04,0.02,0.04,0.0
1,BG,0.18,0.07,0.13,0.02,0.02,0.03,0.05,0.18,0.06,0.04,0.02,0.06,0.02,0.05,0.03,27.0
2,CZ,0.12,0.04,0.06,0.03,0.04,0.03,0.13,0.24,0.03,0.05,0.04,0.06,0.02,0.03,0.03,44.0
3,DK,0.06,0.01,0.05,0.01,0.02,0.25,0.07,0.30,0.04,0.02,0.02,0.04,0.03,0.04,0.03,14.0
4,DEW,0.13,0.02,0.06,0.04,0.03,0.09,0.10,0.21,0.02,0.06,0.02,0.03,0.07,0.04,0.06,17.0
5,DE,0.14,0.02,0.06,0.03,0.03,0.10,0.11,0.20,0.02,0.06,0.02,0.03,0.07,0.04,0.06,17.0
6,DEE,0.18,0.02,0.07,0.03,0.03,0.10,0.13,0.16,0.01,0.06,0.02,0.05,0.06,0.04,0.04,0.0
7,EE,0.20,0.05,0.04,0.07,0.05,0.03,0.04,0.20,0.06,0.05,0.02,0.05,0.02,0.05,0.04,20.0
8,IE,0.09,0.06,0.04,0.05,0.02,0.10,0.13,0.15,0.04,0.02,0.03,0.17,0.03,0.03,0.03,7.0
9,EL,0.27,0.12,0.06,0.05,0.02,0.04,0.07,0.13,0.05,0.01,0.01,0.09,0.05,0.02,0.01,2.0
10,ES,0.13,0.15,0.04,0.05,0.03,0.04,0.11,0.08,0.06,0.03,0.02,0.13,0.04,0.02,0.04,18.0
11,FR,0.09,0.09,0.05,0.06,0.03,0.12,0.08,0.16,0.08,0.02,0.01,0.10,0.02,0.02,0.04,16.0
12,HR,0.17,0.08,0.04,0.05,0.02,0.06,0.06,0.16,0.07,0.06,0.02,0.07,0.02,0.04,0.05,12.0
13,IT,0.15,0.11,0.03,0.03,0.06,0.09,0.07,0.16,0.02,0.03,0.03,0.07,0.05,0.05,0.04,6.0
14,CY,0.17,0.06,0.03,0.07,0.02,0.03,0.18,0.17,0.04,0.01,NaN,0.12,0.06,0.01,0.02,3.0
15,LV,0.14,0.05,0.06,0.06,0.02,0.01,0.07,0.23,0.06,0.03,0.03,0.15,0.03,0.01,0.02,28.0
16,LT,0.13,0.06,0.08,0.05,0.02,0.02,0.06,0.33,0.03,0.02,0.03,0.09,0.01,0.03,0.03,7.0
17,LU,0.06,0.06,0.07,0.07,0.04,0.10,0.09,0.21,0.03,0.03,0.01,0.05,0.07,0.05,0.05,3.0
18,HU,0.14,0.04,0.07,0.04,0.03,0.08,0.10,0.15,0.05,0.04,0.03,0.11,0.06,0.02,0.03,5.0
19,MT,0.11,0.07,0.05,0.06,0.04,0.09,0.18,0.14,0.03,0.02,0.01,0.10,0.04,0.04,0.02,2.0
20,NL,0.05,0.01,0.04,0.03,0.02,0.15,0.17,0.27,0.02,0.02,0.02,0.04,0.05,0.05,0.05,2.0
21,AT,0.15,0.06,0.08,0.04,0.05,0.09,0.10,0.14,0.04,0.03,0.03,0.05,0.05,0.04,0.04,2.0
22,PL,0.09,0.05,0.05,0.03,0.03,0.04,0.05,0.29,0.04,0.07,0.03,0.08,0.05,0.04,0.05,10.0
23,PT,0.07,0.20,0.11,0.04,0.02,0.03,0.05,0.11,0.04,0.02,0.01,0.24,0.02,0.02,0.01,14.0
24,RO,0.11,0.10,0.05,0.07,0.04,0.03,0.05,0.17,0.07,0.06,0.04,0.07,0.04,0.04,0.04,24.0
25,SI,0.17,0.02,0.07,0.04,0.01,0.05,0.12,0.10,0.11,0.04,0.03,0.12,0.02,0.03,0.07,2.0
26,SK,0.14,0.06,0.06,0.04,0.02,0.03,0.06,0.17,0.07,0.06,0.02,0.11,0.04,0.05,0.07,2.0
27,FI,0.14,0.10,0.04,0.03,0.05,0.09,0.03,0.28,0.04,0.02,0.03,0.02,0.05,0.03,0.04,14.0
28,SE,0.09,0.02,0.04,0.02,0.04,0.27,0.06,0.18,0.03,0.02,0.02,0.01,0.11,0.02,0.07,1.0

In [23]:
mapping_df = pd.read_csv('mapping_columns.csv')
mapping_df['raw_phrase'] = mapping_df['raw_phrase'].astype(str).str.lower().str.strip()
mapping_df['clean_phrase'] = mapping_df['clean_phrase'].astype(str).str.lower().str.strip()
        
mapping_df['phrase_len'] = mapping_df['raw_phrase'].str.len()
mapping_df = mapping_df.sort_values(by='phrase_len', ascending=False)
column_replacements = dict(zip(mapping_df['raw_phrase'], mapping_df['clean_phrase']))
mapping_df.to_csv('mapping_columns.csv', index=False)